name: Target Multiple Node.js Versions and Operating Systems
on:
  push:
    - 'client/tests/**'
  pull_request:
    - 'client/tests/**'  

jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - uses: actions/checkout@v1
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome ./client/tests/*.js"